drop type   AUTEUR_T force;
drop type   TAB_REF_AUTEURS ;
drop type   CATALOGUE_T force;
drop type   EXEMPLAIRE_T force;
drop type   TABEXEMPLAIRES_T force;
drop type   BIBLIOTHEQUE_T force;
drop type   ADHERENT_T force;
drop type   TABPRENOMS_T force;
drop type   TAB_REF_BIBLIOTHEQUE force;
drop type   EMPRUNT_T force;
drop type   RESEAU_T force;


CREATE OR REPLACE TYPE AUTEUR_T
/

CREATE OR REPLACE TYPE TAB_REF_AUTEURS AS TABLE OF REF AUTEUR_T ;
/

CREATE OR REPLACE TYPE CATALOGUE_T
/

CREATE OR REPLACE TYPE CATALOGUE_T AS OBJECT(
ID                  NUMBER(4),
TITRE               VARCHAR2(20),
ANNEE_EDITION       DATE,
MAISON_EDITION      VARCHAR2(20),
REF_AUTEURS         TAB_REF_AUTEURS,
DESCRIPTION         CLOB
);
/

CREATE OR REPLACE TYPE EXEMPLAIRE_T AS OBJECT(
ID                  NUMBER(4),
REF_CATALOGUE       REF CATALOGUE_T
);
/

CREATE OR REPLACE TYPE TABEXEMPLAIRES_T AS VARRAY(4) OF EXEMPLAIRE_T ;
/

CREATE OR REPLACE TYPE BIBLIOTHEQUE_T AS OBJECT(
ID                          NUMBER(4),
REGION                      VARCHAR(20),
EXEMPLAIRES                 TABEXEMPLAIRES_T,
ADDRESSE                    VARCHAR(20),
VILLE                       VARCHAR(20)
);
/

CREATE OR REPLACE TYPE ADHERENT_T
/

CREATE OR REPLACE TYPE EMPRUNT_T AS OBJECT(
ID                      NUMBER(4),
REF_ADHERENT            REF ADHERENT_T,
DATE_START              DATE ,
DATE_END                DATE ,
DATE_RETOUR             DATE ,
REF_EXEMPLAIRE          REF EXEMPLAIRE_T
);
/

CREATE OR REPLACE TYPE TABPRENOMS_T AS VARRAY(4) OF VARCHAR2(40);
/

CREATE OR REPLACE TYPE TAB_REF_BIBLIOTHEQUE AS TABLE OF REF BIBLIOTHEQUE_T
/

CREATE OR REPLACE TYPE ADHERENT_T AS OBJECT(
NUMERO_ADHERENT            NUMBER(4),
NOM                        VARCHAR2(20),
PRENOMS                    TABPRENOMS_T,
REF_BIBLIOTHEQUE           TAB_REF_BIBLIOTHEQUE,
ADRESSE                    VARCHAR2(20),
PHONE                      VARCHAR2(20),
EMAIL                      VARCHAR2(20),
ANNEE_DE_NAISSANCE         DATE,
DATE_D_ADHESION            DATE,
VILLE                      VARCHAR2(20)
);
/

CREATE OR REPLACE TYPE AUTEUR_T AS OBJECT(
ID                          NUMBER(4),
NOM                         VARCHAR2(20),
PRENOMS                     TABPRENOMS_T,
DATE_DE_NAISSANCE           DATE,
DATE_DE_DECES               DATE,
NATIONALITE                 VARCHAR(20),
VILLE                       VARCHAR(20),
BIOGRAPHIE                  CLOB
);
/


CREATE OR REPLACE TYPE TAB_REF_BIBLIOTHEQUE_T AS TABLE OF REF BIBLIOTHEQUE_T
/

CREATE OR REPLACE TYPE RESEAU_T AS OBJECT(
ID                          NUMBER(4),
NOM                         VARCHAR(20),
BIBLIOTHEQUES               TAB_REF_BIBLIOTHEQUE_T
);
/



